NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/[(${caCertName})].pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/[(${caCertName})].pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/[(${caCertName})].pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/[(${caCertName})].pem
    OrganizationalUnitIdentifier: orderer